import profil from '../assets/profil.jpg'
export const Annoncesdata = [
    {
        id: 0,
        delay:'20min',
        genre:'H',
        langue:'FR',
        metier: 'Soudeur',
        pseudo: 'bryan',
        type: 'Emploi cdd',
        ville: 'Adamaoua',
        domaine: 'Transport et Logistique',
        emploidt:'Temps plein',
        cover: profil,
        diplome: 'Bac ou EQ',
        experience: 'Senior',
        remuneration: 'Avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 1,
        delay:'20min',
        genre:'F',
        langue:'EN',
        metier: 'Electricien',
        pseudo:'loic',
        type:'Emploi cdi',
        ville:'Garoua',
        domaine:'Douane et Transit',
        emploidt: 'Temp partiel',
        cover: profil,
        diplome: 'Bac ou EQ',
        experience: 'Senior',
        remuneration: 'Avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 2,
        delay:'20min',
        genre:'H',
        langue:'FR',
        metier: 'Developpeur',
        pseudo: 'mark',
        type:'Stage proffessionnel',
        ville:'Ebolowa',
        domaine:'Transport et Logistique',
        emploidt:'Temps partiel',
        cover: profil,
        diplome: 'Bac ou EQ',
        experience: 'Senior',
        remuneration: 'Avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 3,
        delay:'20min',
        genre:'F',
        langue:'EN',
        metier: 'Manoeuvre',
        pseudo: 'Louis',
        type: 'Stage academique',
        ville: 'Douala',
        domaine: 'Industriel',
        emploidt: 'Temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'Senior',
        remuneration: 'Avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 4,
        delay:'20min',
        langue:'EN',
        genre:'H',
        metier: 'Agent comptable',
        pseudo: 'henri',
        type: 'job',
        ville: 'Yaounde',
        domaine: 'Agriculture',
        emploidt: 'Temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'Senior',
        remuneration: 'Avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 5,
        delay:'20min',
        genre:'F',
        langue:'FR',
        metier: 'Soudeur',
        pseudo: 'bryan',
        type: 'Emploi cdd',
        ville: 'Adamaoua',
        domaine: 'Elevage',
        emploidt:'Temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'Senior',
        remuneration: 'Avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 6,
        delay:'20min',
        genre:'H',
        langue:'EN',
        metier: 'Electricien',
        pseudo:'loic',
        type:'emploi cdi',
        ville:'garoua',
        domaine:'informatique',
        emploidt: 'temp partiel',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 7,
        delay:'20min',
        genre:'F',
        langue:'FR',
        metier: 'developpeur',
        pseudo: 'mark',
        type:'stage proffessionnel',
        ville:'ebolowa',
        domaine:'soins corporel',
        emploidt:'temps partiel',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 8,
        delay:'20min',
        genre:'H',
        langue:'EN',
        metier: 'manoeuvre',
        pseudo: 'Louis',
        type: 'stage academique',
        ville: 'douala',
        domaine: 'industriel',
        emploidt: 'tamps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 9,
        delay:'20min',
        genre:'F',
        langue:'FR',
        metier: 'agent comptable',
        pseudo: 'henri',
        type: 'job',
        ville: 'yaounde',
        domaine: 'agriculture',
        emploidt: 'temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 10,
        metier: 'Soudeur',
        genre:'H',
        langue:'EN',
        pseudo: 'bryan',
        type: 'emploi cdd',
        ville: 'adamaoua',
        domaine: 'elevage',
        emploidt:'temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 11,
        metier: 'Electricien',
        genre:'F',
        langue:'EN',
        pseudo:'loic',
        type:'emploi cdi',
        ville:'garoua',
        domaine:'informatique',
        emploidt: 'temp partiel',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 12,
        metier: 'developpeur',
        genre:'F',
        langue:'EN',
        pseudo: 'mark',
        type:'stage proffessionnel',
        ville:'ebolowa',
        domaine:'soins corporel',
        emploidt:'temps partiel',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
        description: 'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile'
    },
    {
        id: 13,
        metier: 'manoeuvre',
        genre:'F',
        langue:'EN',
        pseudo: 'Louis',
        type: 'stage academique',
        ville: 'douala',
        domaine: 'industriel',
        emploidt: 'tamps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
    {
        id: 14,
        metier: 'agent comptable',
        genre:'F',
        langue:'EN',
        pseudo: 'henri',
        type: 'job',
        ville: 'yaounde',
        domaine: 'agriculture',
        emploidt: 'temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
    {
        id: 15,
        metier: 'Soudeur',
        genre:'F',
        langue:'EN',
        pseudo: 'bryan',
        type: 'emploi cdd',
        ville: 'adamaoua',
        domaine: 'elevage',
        emploidt:'temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
    {
        id: 16,
        metier: 'Electricien',
        genre:'F',
        langue:'EN',
        pseudo:'loic',
        type:'emploi cdi',
        ville:'garoua',
        domaine:'informatique',
        emploidt: 'temp partiel',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
    {
        id: 17,
        metier: 'developpeur',
        genre:'F',
        langue:'EN',
        pseudo: 'mark',
        type:'stage proffessionnel',
        ville:'ebolowa',
        domaine:'soins corporel',
        emploidt:'temps partiel',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
    {
        id: 18,
        metier: 'manoeuvre',
        genre:'F',
        langue:'EN',
        pseudo: 'Louis',
        type: 'stage academique',
        ville: 'douala',
        domaine: 'industriel',
        emploidt: 'tamps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
    {
        id: 19,
        metier: 'agent comptable',
        genre:'F',
        langue:'EN',
        pseudo: 'henri',
        type: 'job',
        ville: 'yaounde',
        domaine: 'agriculture',
        emploidt: 'temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
    {
        id: 20,
        metier: 'Soudeur',
        genre:'F',
        langue:'EN',
        pseudo: 'bryan',
        type: 'emploi cdd',
        ville: 'adamaoua',
        domaine: 'elevage',
        emploidt:'temps plein',
        cover: profil,
        diplome: 'Bac c',
        experience: 'senior',
        remuneration: 'avec',
    },
]