import profil from '../assets/profil.jpg'
export const Independantsdata = [
    {
        id: 0,
        delay:'20min',
        pseudo: 'Dario',
        experience: 'Debutant',
        profession: 'Electricien',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile',
        genre:'H',
        disponibilité: 'disponible',
        langue:'EN',
    },
    {
        id: 1,
        delay:'20min',
        pseudo: 'Smith',
        experience: 'Debutant',
        profession: 'Consultant-marketing-digital',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Licence',
        presentation:'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile',
        genre:'F',
        disponibilité: 'occupé',
        langue:'FR',
    },
    {
        id: 2,
        delay:'20min',
        pseudo: 'Alias',
        experience: 'Expert',
        profession: 'Menusier',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile',
        genre:'H',
        disponibilité: 'disponible',
        langue:'EN',
    },
    {
        id: 3,
        delay:'20min',
        pseudo: 'Smithologue',
        experience: 'Debutant',
        profession: 'Soudeur',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile',
        genre:'F',
        disponibilité: 'occupé',
        langue:'FR',
    },
    {
        id: 4,
        delay:'20min',
        pseudo: 'Karisma',
        experience: 'Expert',
        profession: 'peintre',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Maitrise',
        presentation:'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile',
        genre:'H',
        langue:'EN',
        disponibilité: 'disponible'
    },
    {
        id: 5,
        delay:'20min',
        pseudo: 'Dario',
        experience: 'Debutant',
        profession: 'Electricien',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Maitrise',
        presentation:'bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobilebonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile bonjour je suis dariio smith alias le karisma un jeune entrepreneur base au cameroun avec plusieurs annees d exxperience dans la developpement web et le developpement mobile',
        genre:'F',
        langue:'FR',
        disponibilité: 'occupé'
    },
    {
        id: 6,
        pseudo: 'Smith',
        experience: 'Debutant',
        profession: 'Plombier',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Maitrise',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 7,
        delay:'20min',
        pseudo: 'Alias',
        experience: 'Expert',
        profession: 'Menusier',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'H',
        langue:'FR',
        disponibilité: 'disponible'
    },
    {
        id: 8,
        delay:'20min',
        pseudo: 'Smithologue',
        experience: 'Debutant',
        profession: 'Soudeur',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Maitrise',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 9,
        delay:'20min',
        pseudo: 'Karisma',
        experience: 'Expert',
        profession: 'peintre',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'H',
        langue:'FR',
        disponibilité: 'disponible'
    },
    {
        id: 10,
        delay:'20min',
        pseudo: 'Dario',
        experience: 'Debutant',
        profession: 'Electricien',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 11,
        delay:'20min',
        pseudo: 'Smith',
        experience: 'Debutant',
        profession: 'Plombier',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'H',
        langue:'FR',
        disponibilité: 'disponible'
    },
    {
        id: 12,
        pseudo: 'Alias',
        experience: 'Expert',
        profession: 'Menusier',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 13,
        pseudo: 'Smithologue',
        experience: 'Debutant',
        profession: 'Soudeur',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 14,
        pseudo: 'Karisma',
        experience: 'Expert',
        profession: 'peintre',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 15,
        pseudo: 'Dario',
        experience: 'Debutant',
        profession: 'Electricien',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 16,
        pseudo: 'Smith',
        experience: 'Debutant',
        profession: 'Plombier',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Bac',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 17,
        pseudo: 'Alias',
        experience: 'Expert',
        profession: 'Menusier',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Licence',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 18,
        pseudo: 'Smithologue',
        experience: 'Debutant',
        profession: 'Soudeur',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Licence',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    },
    {
        id: 19,
        pseudo: 'Karisma',
        experience: 'Expert',
        profession: 'peintre',
        cover: profil,
        ville: 'Douala',
        quartier: 'Makepe',
        diplome:'Licence',
        presentation:'je suis dario smith alias le smithologue',
        genre:'F',
        langue:'EN',
        disponibilité: 'occupé'
    } 
]